version: "3"
services:


  cde-box-daemon: 
#    image: markw/cde-box-daemon:0.3.0   # to use the version 1 CDE models
    image: markw/cde-box-daemon:0.5.0    # to use the version 2 CDE models with Hefesto
    container_name: cde-box-daemon
    environment:
      GraphDB_User: ${GraphDB_User}
      GraphDB_Pass: ${GraphDB_Pass}
      baseURI: ${baseURI}
    depends_on:
      - hefesto
      - yarrrml-rdfizer
    ports:
      - 4567:4567
    volumes:
        - ./data:/data
        - ./config:/config
    networks:
      - default
      - graphdb_net 
        
 
  hefesto:
    image: pabloalarconm/hefesto_fiab:0.0.6
    hostname: hefesto
    # ports:
    #   - "8000:8000"
    volumes:
      - ./data:/code/data

  yarrrml-rdfizer:
    image: markw/yarrrml-rml-ejp:0.0.3
    container_name: yarrrml-rdfizer
    hostname: yarrrml-rdfizer
    environment:
      # (nquads (default), trig, trix, jsonld, hdt, turtle)
      - SERIALIZATION=nquads
#    ports:
#      - "4567:4567"
    volumes:
      - ./data:/mnt/data
    networks:
      - default
      - graphdb_net 
    
# volumes:
#   graphdb-data:
#     external: true
        
# Define networks here .  Note that GraphDB must already be running with a database called 'cde'
networks:
  graphdb_net:
#    external: true
